#!/usr/bin/env bash
# Package a release claim YAML for a version tag (Phase D).
# Usage: scripts/package-release-claim.sh <tag> [commit-sha]
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tag="${1:?tag required (e.g. 0.1.0 or v0.1.0)}"
tag="${tag#v}"
commit="${2:-}"
if [[ -z "$commit" ]]; then
  commit="$(git -C "$root" rev-parse HEAD)"
fi
if [[ ! "$commit" =~ ^[0-9a-f]{40}$ ]]; then
  echo "commit must be a 40-char hex SHA (got '$commit')" >&2
  exit 1
fi
created="$(date -u +%F)"
out="$root/engineering/claims/${tag}.yaml"
mkdir -p "$root/engineering/claims"

cat >"$out" <<EOF
claims:
  - id: CLAIM-${tag}
    tag: ${tag}
    commit: "${commit}"
    claim_massimo: architectural-prototype
    gates:
      - GATE-DISK-WIRE-VERSIONS
      - GATE-CMAKE-INSTALL
      - GATE-THREAT-SUPPLY
      - GATE-VERSION-LIFECYCLE
    evidence:
      - workflow: release-compat.yml
      - workflow: supply-chain.yml
      - workflow: assurance.yml
      - path: engineering/compatibility/n-n1-matrix.yaml
      - path: tests/fixtures/released/${tag}/
    created: "${created}"
    notes: >
      Generated by scripts/package-release-claim.sh. Claim ceiling stays
      architectural-prototype until alpha gates are accepted with retained evidence.
EOF

echo "Wrote $out"
