include_guard(GLOBAL)

include(CheckCXXCompilerFlag)

function(glyphastore_enable_hardening target)
    if(NOT GLYPHASTORE_ENABLE_HARDENING)
        return()
    endif()
    foreach(flag IN ITEMS -fstack-protector-strong -fPIE)
        string(MAKE_C_IDENTIFIER "${flag}" flag_id)
        check_cxx_compiler_flag("${flag}" "HAS_${flag_id}")
        if("HAS_${flag_id}")
            target_compile_options(${target} PRIVATE "${flag}")
        endif()
    endforeach()
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        target_compile_definitions(${target} PRIVATE _FORTIFY_SOURCE=3)
        target_link_options(${target} PRIVATE -Wl,-z,relro -Wl,-z,now)
    endif()
endfunction()
