include_guard(GLOBAL)

function(glyphastore_resolve_sanitizers output_variable)
    if(GLYPHASTORE_ENABLE_TSAN AND (GLYPHASTORE_ENABLE_ASAN OR GLYPHASTORE_ENABLE_UBSAN))
        message(FATAL_ERROR "TSan cannot be combined with ASan/UBSan in this project")
    endif()
    if(NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        set(${output_variable} "" PARENT_SCOPE)
        return()
    endif()
    if(GLYPHASTORE_ENABLE_POINTER_PAIR_SANITIZER AND NOT GLYPHASTORE_ENABLE_ASAN)
        message(FATAL_ERROR "Pointer compare/subtract sanitizers require ASan")
    endif()
    set(sanitizers "")
    if(GLYPHASTORE_ENABLE_ASAN)
        list(APPEND sanitizers address)
    endif()
    if(GLYPHASTORE_ENABLE_UBSAN)
        list(APPEND sanitizers undefined)
    endif()
    if(GLYPHASTORE_ENABLE_POINTER_PAIR_SANITIZER)
        include(CheckCXXSourceCompiles)
        set(saved_required_flags "${CMAKE_REQUIRED_FLAGS}")
        set(saved_required_link_options "${CMAKE_REQUIRED_LINK_OPTIONS}")
        set(CMAKE_REQUIRED_FLAGS "${CMAKE_REQUIRED_FLAGS} -fsanitize=address,pointer-compare,pointer-subtract")
        list(APPEND CMAKE_REQUIRED_LINK_OPTIONS -fsanitize=address,pointer-compare,pointer-subtract)
        check_cxx_source_compiles("int main() { return 0; }" GLYPHASTORE_HAS_POINTER_PAIR_SANITIZER)
        set(CMAKE_REQUIRED_FLAGS "${saved_required_flags}")
        set(CMAKE_REQUIRED_LINK_OPTIONS "${saved_required_link_options}")
        if(NOT GLYPHASTORE_HAS_POINTER_PAIR_SANITIZER)
            message(FATAL_ERROR
                "GLYPHASTORE_ENABLE_POINTER_PAIR_SANITIZER=ON, but the selected toolchain "
                "does not link pointer compare/subtract instrumentation")
        endif()
        list(APPEND sanitizers pointer-compare pointer-subtract)
    endif()
    if(GLYPHASTORE_ENABLE_TSAN)
        list(APPEND sanitizers thread)
    endif()
    set(${output_variable} "${sanitizers}" PARENT_SCOPE)
endfunction()

function(glyphastore_enable_sanitizers target)
    glyphastore_resolve_sanitizers(sanitizers)
    if(sanitizers)
        list(JOIN sanitizers "," sanitizer_flags)
        target_compile_options(${target} INTERFACE -fno-omit-frame-pointer "-fsanitize=${sanitizer_flags}")
        target_link_options(${target} INTERFACE "-fsanitize=${sanitizer_flags}")
    endif()
endfunction()
