include_guard(GLOBAL)

function(glyphastore_resolve_sanitizers output_variable)
    if(GLYPHASTORE_ENABLE_TSAN AND (GLYPHASTORE_ENABLE_ASAN OR GLYPHASTORE_ENABLE_UBSAN))
        message(FATAL_ERROR "TSan cannot be combined with ASan/UBSan in this project")
    endif()
    if(NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        set(${output_variable} "" PARENT_SCOPE)
        return()
    endif()
    set(sanitizers "")
    if(GLYPHASTORE_ENABLE_ASAN)
        list(APPEND sanitizers address)
    endif()
    if(GLYPHASTORE_ENABLE_UBSAN)
        list(APPEND sanitizers undefined)
    endif()
    if(GLYPHASTORE_ENABLE_TSAN)
        list(APPEND sanitizers thread)
    endif()
    set(${output_variable} "${sanitizers}" PARENT_SCOPE)
endfunction()

function(glyphastore_enable_sanitizers target)
    glyphastore_resolve_sanitizers(sanitizers)
    if(sanitizers)
        list(JOIN sanitizers "," sanitizer_flags)
        target_compile_options(${target} INTERFACE -fno-omit-frame-pointer "-fsanitize=${sanitizer_flags}")
        target_link_options(${target} INTERFACE "-fsanitize=${sanitizer_flags}")
    endif()
endfunction()
